# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-26 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bytes', models.CharField(max_length=10000000)),
                ('eid', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_task_id', models.CharField(max_length=1000)),
                ('sender_id', models.CharField(max_length=1000)),
                ('submit_image_id', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='eid',
            field=models.CharField(default='kek', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='eid',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
