# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-27 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0003_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='img_type',
            field=models.CharField(default='png', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='bytes',
            field=models.CharField(max_length=1000000000),
        ),
    ]
