# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-27 12:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0004_auto_20170327_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='submit_number',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
