# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-28 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0005_submission_submit_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_expire',
            field=models.CharField(default=-1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='session_id',
            field=models.CharField(default='-1', max_length=1000),
            preserve_default=False,
        ),
    ]
