# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-28 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0006_auto_20170328_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='eid',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
