# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-02 08:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0007_submission_eid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='login',
        ),
    ]
