# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-08 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0008_auto_20170402_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expire_date',
            field=models.CharField(default=2, max_length=1000),
            preserve_default=False,
        ),
    ]
