# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-16 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0009_task_expire_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
