# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-04-21 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PQDB', '0010_user_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image_id',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
