# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-24 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('difficuilty', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=1000)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PUsers.User')),
            ],
        ),
    ]
